### ISSUE TITLE
Cannot docker run swot_ai_service

### ISSUE THREAD

**Issue by Medicjue** [HCTsai/MLOps_DevOpsDays_2022#1]
Hi, I followed the README to build the env., however, I stucked when I execute the command "docker run  --name swot_ai_service -p 5000:5000 swot_ai:v1", the error msg:
```
Downloading: 100%|██████████| 19.0/19.0 [00:00<00:00, 17.4kB/s]
Downloading: 100%|██████████| 689/689 [00:00<00:00, 684kB/s]
Downloading: 100%|██████████| 107k/107k [00:00<00:00, 275kB/s]
Downloading: 100%|██████████| 263k/263k [00:00<00:00, 456kB/s]
Downloading: 100%|██████████| 2.00/2.00 [00:00<00:00, 1.65kB/s]
Downloading: 100%|██████████| 112/112 [00:00<00:00, 69.5kB/s]
Downloading: 100%|██████████| 393M/393M [00:31<00:00, 12.9MB/s]
Some weights of the model checkpoint at hfl/chinese-roberta-wwm-ext were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2022-09-21 16:20:57.723 | DEBUG    | text2vec.sentence_model:__init__:74 - Use device: cpu
/usr/local/lib/python3.8/site-packages/xgboost/compat.py:93: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
```
The status of the docker container is "Exited (137) 49 seconds ago"

Wondering if you can assist me to fix the situation, thank you!

**Comment by HCTsai** [comment]
The logs you provided are not contain error message clearly.

First, it showed that the container downloaded the pre-trained machine learning model. 
(It may takes few minutes when you first run your docker container.)

Secondly, it load some python packages in your container and showed some normal information.

There's no clear errors. 
Could you try to start the container again or provide more messages ?

**Comment by HCTsai** [comment]
I found two problems in previous code:

1. line 61-63 in app.py  do not use Counter of prometheus_client properly. This issue cause the docker container not work properly.
2. packages in requirements.txt contain version conflict

I have fixed them and update new version codes.
Maybe you can try to build a new docker image and run the container again.
